FROM geertjohan/go1.1.2:latest

MAINTAINER Geert-Johan Riemer

# install gomatrix
run	go get github.com/GeertJohan/gomatrix
run	go install github.com/GeertJohan/gomatrix

# set default cmd
cmd	gomatrix
